server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs?useSSL=false
    username: root
    password: xuxin158263
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: bbsService
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

user_service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - user_service
